### ISSUE TITLE
Improve the CONTRIBUTING.md

### ISSUE THREAD

**Issue by lee00286** [JuanVqz/my_school#10]
**Is your feature request related to a problem? Please describe.**

There is more area of improvement in CONTRIBUTING.md, so opening this issue

**Describe the solution you'd like**

Improve the wording on branch convention for new pull requests, in the CONTRIBUTING file

**Describe alternatives you've considered**

I will edit CONTRIBUTING.md with some references on [contributing to forem](https://docs.dev.to/contributing/forem/)

**Comment by JuanVqz** [comment]
PR #11
