### ISSUE TITLE
Project "About" description

### ISSUE THREAD

**Issue by maldad** [JuanVqz/my_school#12]
A suggestion for the About description:

**Current:**
Since the current pandemic, we need a way to go ahead and still getting better for our kids that is the reason we are creating this virtual school in order to get available teachers with students in virtual classrooms.

**Suggestion:**
Due to the global pandemic we need a way to keep going with our kids. This is the reason we are creating a virtual school where teachers will be available along with students in virtual classrooms.

**Comment by JuanVqz** [comment]
@maldad Thank you for your suggestion it is better than we already have, I'll approve it thank you and you are welcome to the following contributions :1st_place_medal:
